apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/app-1

components:
  - ../../../variants/staging/app-1
  - ../../../variants/staging-euw1/app-1


patchesStrategicMerge:
- deployment.yaml
