apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/app-1
- secret.sops.yaml

components:
  - ../../../variants/staging/app-1
  - ../../../variants/staging-nane1/app-1


patchesStrategicMerge:
- deployment.yaml
